version: '3.8'

services:

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.7
    command: start
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data

